### ISSUE TITLE
Conference slot proposal

### ISSUE THREAD

**Issue by xatapult** [xproc/Workshop-2-2019#1]
Hi all. Here is my input for the regular XML Prague 2019 conference slot about XProc 3.0. This is what I currently plan to submit using the CFP, after getting your consent.

Questions:

1. Ok? More? Different? 
2. Although I took this task on me (including writing the paper and creating a presentation), should I list you as co-authors (in the CFP)? We're all in this together, aren't we?

---

Title: **Excellent XProc 3.0** (is this too playful? A straight "XProc 3.0 status update" sounds so boring... )

**Abstract:**
Since 2017, the W3C XProc Next Community Group has been busy specifying a new version of the XProc standard, version 3.0. By XML Prague 2019 we’re planning to have a core specification ready for “last call”. This talk will present an overview of the XProc language and its principles and link this to the changes made in V3.0. 

**Contents:**

Since 2017, the W3C XProc Next Community Group has been busy specifying a new version of the XProc standard, version 3.0. In parallel, two XProc 3.0 processors are developed and a Programmer’s Reference written. Work still needs to be done on the step library. We hope to wrap things up before the end of 2019. The core committee consists of Normal Walsh, Achim Berndzen, Gerrit Imsieke and Erik Siegel.

XProc V1.0 served as the starting point for V3.0 but has been modernized, changed and made more consistent in many ways. However, XProc is not a very well-known standard, so we would like to present these changes linked to explaining some of the core features and principles of the language. So not just a list of changes (that will fall on barren ground if you don’t really know the language) but more an “XProc principles overview” and link this overview to the changes we made.

To show its not vaporware, we’ll demonstrate that the two V3.0 processors, Calabash and Morgana, although still under construction, are actually working and processing documents.

**Comment by xml-project** [comment]
1) I like the title
2) No sure, but may be there should be a sentence on the overall goals of 3.0 like improve usability, align with new technologies (XPath 3.1) - but its up to you.
3) Could you please change the name of my processor to "MorganaXProc" ('Morgana' is a registered name in some branches). Btw. I think "XMLCalabash" would be more correct.
4) If you check the paper in, please remember also to request for a slot on unconference day.

**Comment by xatapult** [comment]
1. +1
1. Will add something
1. Will do
1. They need  a description. What are we going to do, can anybody formulate something, I'm happy to do the request.

**Comment by xml-project** [comment]
add 3: Thanks
add 4: Will write proposal on Friday. Maybe we could talk about it shortly on Thursday. As a blue print, I think last years text, is useable.

To remind every one:

XProc 3.0

Organized by Achim Berndzen, Gerrit Imsieke, and Norman Walsh.

The XProc next community group has worked hard over the past year to
develop XProc 3.0, the next version of XProc: An XML Pipeline
Language (W3C Recommendation from 2010). The new version is now
clearly showing up on the horizon.

Highlights are non-XML data processing, typed variables and options,
many syntactic improvements, and, yes, removal of parameter input
ports! Parameter ports have been replaced by XDM maps.

The members of the editors group will present the current state of
XProc 3.0. We’ll also discuss implementations, the test suite, and
other topics as proposed by the attendees.

Please join us in this session of XML Prague's unconference day to
discuss the latest news about XProc 3.0.

============================================================

**Comment by ndw** [comment]
This all looks good to me. Please list my processor as "XML Calabash" for no profound reason except that that's the domain name.

**Comment by xatapult** [comment]
All right gentleman, I've submitted for a 30min slot on the conference. You're all registered as co-authors.
