### ISSUE TITLE
Text for unconference day slot

### ISSUE THREAD

**Issue by xml-project** [xproc/Workshop-2-2019#2]
XProc 3.0 live

organized by Achim Berndzen, Gerrit Imsieke, Erik Siegel and Norman Walsh.

XProc 3.0 brings many improvements to XML pipeline processing, e.g.: 
- In addition to XML document now text documents, JSON documents, and binary documents can flow between the steps of your pipelines.  
- Variables and options are now typed, XPath 3.1 is used as expression languages, maps and arrays are usable in your pipelines.
- Many syntactic short cuts allow you to write much shorter pipelines.

The editors of the XProc 3.0 specification will give you an overview over XProc 3.0 and discuss example pipelines demonstrating the basic improvements. Additionally two implementations will be shown for the first time.

While the core specification of XProc 3.0 are almost finished, the specification of the step library is still work in progress. In this topic the editors are looking for your advice on which step types you would like to see in the standard library.

Please join us in this session of XML Prague’s unconference day to discuss the latest news about XProc 3.0.

**Comment by gimsieke** [comment]
`s/is used as expression languages/is used as expression language/`
Otherwise, agree. A native speaker should check the wording though (for ex., is there a slight difference in meaning between “usable” and “can be used”?)

**Comment by xml-project** [comment]
@gimsieke Thanks, will correct it.

**Comment by xml-project** [comment]
Done!
