### ISSUE TITLE
Does folks who can't join workshop be welcome to share beers ?

### ISSUE THREAD

**Issue by cmarchand** [xproc/Workshop-2-2019#5]
There are many of us that cannot join the community group for the workshop.
Will the participants welcome regular members on wednesday evening for post-workshop beers ?

Maybe with a special tweeter hashtag ...

**Comment by ndw** [comment]
If you can't get to Prague in time for the workshop, you are more than welcome to join us for dinner and/or beer in the evening. We'll tweet something about our plans.
